import Head from "next/head";
import priya from "../public/priya.jpeg";
import Image from "next/image";
import { DarkModeProvider, useDarkMode } from '../context/DarkModeContext';

const Home = () => {
  const { darkMode } = useDarkMode();

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <div className="text-center p-10 py-10">
            <h1 className="text-5xl py-2 bg-gradient-to-r from-blue-500 to-teal-500 bg-clip-text text-transparent font-medium dark:from-teal-400 dark:to-blue-500 md:text-6xl">
              Priya Samanta
            </h1>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Aspiring Software Developer
            </h3>
            <div className="relative mx-auto mt-20 h-96 w-96 md:h-144 md:w-144">
              <div className="absolute inset-0 bg-gradient-to-r from-blue-500 to-teal-500 rounded-full p-2 md:p-4">
                <div className="bg-white dark:bg-gray-900 rounded-full overflow-hidden h-full w-full">
                  <Image alt="" src={priya} layout="fill" objectFit="cover" className="rounded-full" />
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}

const App = () => (
  <DarkModeProvider>
    <Home />
  </DarkModeProvider>
);

export default App;
